name: Hypertrons CI

on: [push, pull_request]

env:
  SLACK_CHANNEL: cicd
  SLACK_COLOR: '#008000'
  SLACK_ICON: http://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_MESSAGE: Project `${{ github.repository }}` `${{ github.event_name }}` by `${{ github.actor }}` build `success`.
  SLACK_TITLE: Message
  SLACK_USERNAME: GitHub Actions
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      run: echo ${{ env.SLACK_WEBHOOK }}
      env:
        CI: true
    - name: Build Success
      uses: rtCamp/action-slack-notify@v2.0.0
      if: success()
    - name: Build Failure
      uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: Project `${{ github.repository }}` build `failure`.
    - name: Build Cancelled
      uses: rtCamp/action-slack-notify@v2.0.0
      if: cancelled()
      env:
        SLACK_COLOR: '#FFFF00'
        SLACK_MESSAGE: Project `${{ github.repository }}` build `cancelled`.
